version: 2.1
orbs:
  ruby: circleci/ruby@2.0.1
jobs:
  test-ruby:
    # Install gems, run rails tests
    docker:
      - image: cimg/ruby:3.2-node
    steps:
      - checkout
      - ruby/install-deps
      - run:
          name: rails test
          command: bundle exec rails test
  deploy:
    # Example deploy job
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: Deploy Application
          command: ./deploy.sh
workflows:
  build-and-test:
    jobs:
      - test-ruby
      - deploy:
          requires:
            - test-ruby
